class ContextManager:
    """
    Manages short-term conversation memory for users.
    Stores the last N interactions to provide context for intent resolution.
    """
    def __init__(self, max_history=5):
        self.max_history = max_history
        # Dictionary to store conversation history: user_id -> list of interactions
        self.conversations = {}

    def update_context(self, user_id, user_message, intent, bot_response):
        """
        Updates the conversation history for a user.
        
        Args:
            user_id (str): Unique identifier for the user.
            user_message (str): The message sent by the user.
            intent (str): The detected intent of the message.
            bot_response (str): The response generated by the bot.
        """
        if user_id not in self.conversations:
            self.conversations[user_id] = []
        
        interaction = {
            'user_message': user_message,
            'intent': intent,
            'bot_response': bot_response
        }
        
        self.conversations[user_id].append(interaction)
        
        # Trim history if it exceeds max_history
        if len(self.conversations[user_id]) > self.max_history:
            self.conversations[user_id].pop(0)

    def get_context(self, user_id):
        """
        Retrieves the conversation history for a user.
        
        Args:
            user_id (str): Unique identifier for the user.
            
        Returns:
            list: A list of previous interactions.
        """
        return self.conversations.get(user_id, [])

    def clear_context(self, user_id):
        """
        Clears the conversation history for a user.
        """
        if user_id in self.conversations:
            del self.conversations[user_id]
